stages:
  dataset:
    cmd: python .\src\stages\dataset.py --config params.yaml
    deps:
      - .\src\stages\dataset.py
    params:
      - data_load
      - base
      - data_split
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  featurize:
    cmd: python .\src\stages\featurize.py --config params.yaml
    deps:
      - .\src\stages\featurize.py
      - data/processed/train.csv
      - data/processed/test.csv
    params:
      - data_split
      - featurize
    outs:
      - data/processed/train_features.csv
      - data/processed/test_features.csv

  train:
    cmd: python .\src\stages\train.py --config params.yaml
    deps:
      - .\src\stages\train.py
      - data/processed/train_features.csv
      - data/processed/test_features.csv
    params:
      - train
      - featurize
      - base
    outs:
      - models/model.joblib

  evaluate:
    cmd: python .\src\stages\evaluate.py --config params.yaml
    deps:
      - .\src\stages\evaluate.py
      - models/model.joblib
      - data/processed/test_features.csv
    params:
      - evaluate
      - featurize
      - base
      - train
    metrics:
    - evaluation.json:
        cache: false
    plots:
    - reports/confusion_matrix.png
