base:
  random_state: 42
  target_column: class

visualize:
  output_dir: reports/viz/

data_load:
  raw_data: data/raw/diabetes_data.csv

data_split:
  test_size: 0.2
  output_train_path: data/processed/train.csv
  output_test_path: data/processed/test.csv

featurize:
  output_train_features_path: data/processed/train_features.csv
  output_test_features_path: data/processed/test_features.csv

train:
  estimator_name: xgboost

  model_path: models/model.joblib

  estimators:
    xgboost:
      params:
        eval_metric: logloss
        n_estimators: 20
        max_depth: 10
        learning_rate: 0.1
        objective: binary:logistic
        seed: 42

evaluate:
  reports_dir: reports
  metrics_file: "metrics.json"
  confusion_matrix_file: "confusion_matrix.png"
