base:
  random_state: 42
  target_column: class

visualize:
  output_dir: reports/viz/

data_load:
  raw_data: data/raw/diabetes_data.csv

data_split:
  test_size: 0.2
  output_train_path: data/processed/train.csv
  output_test_path: data/processed/test.csv

featurize:
  output_train_features_path: data/processed/train_features.csv
  output_test_features_path: data/processed/test_features.csv

train:

evaluate:
  reports_dir: reports
  metrics_file: "metrics.json"
